apiVersion: v1
kind: Pod 
metadata: 
  name: vis
  labels:
    env: prod
    version: v1.1.1
spec: 
  containers:
  - name: vis-img
    image: dineshkumarv1/vis-image
    ports:
    - containerPort: 8080
    - containerPort: 80  
